sude: required
#provide copy of docker
services:
    - docker

before_install:
    - docker build -t dheeraj/docker-react -f Dockerfile.div .


script:
    - docker run dheeraj/docker-react npm run test -- --coverage